#!/usr/bin/env bash
# Ticket 06: vendor the baseline Rime data set into vendor/rime-baseline/.
#
# Baseline set: rime-prelude (default/key_bindings/punctuation/symbols),
# rime-luna-pinyin (schemas + dictionary), rime-essay (essay.txt language
# model), and OpenCC conversion data (configs + .ocd2 dictionaries, the
# latter generated by a host build of the opencc tools from librime's
# submodule — no external downloads).
#
# Prereqs: scripts/rime-data/fetch-data.sh and scripts/librime/fetch.sh
# (the opencc submodule must be present).
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
S="$ROOT/.scratch"
DEST="$ROOT/vendor/rime-baseline"
OPENCC="$S/librime/deps/opencc"
HOST_BUILD="$S/build-host-opencc"

log() { printf '\n\033[1m== %s\033[0m\n' "$*"; }

# --- 1. copy baseline YAML/text assets ---
log "copy prelude / luna / essay"
rm -rf "$DEST"
mkdir -p "$DEST"
cp "$S/rime-prelude/default.yaml" "$S/rime-prelude/key_bindings.yaml" \
   "$S/rime-prelude/punctuation.yaml" "$S/rime-prelude/symbols.yaml" "$DEST/"
cp "$S"/rime-luna-pinyin/*.yaml "$DEST/"
cp "$S/rime-essay/essay.txt" "$DEST/"

# --- 2. host-build opencc tools and generate .ocd2 dictionaries ---
# The iOS deps build sed-disables opencc's tools/ and data/ subdirectories
# in the submodule; restore them for the host build (the iOS script
# re-applies its patches idempotently on its next run).
log "host-build opencc tools"
git -C "$OPENCC" checkout -- src/CMakeLists.txt CMakeLists.txt
cmake -S "$OPENCC" -B "$HOST_BUILD" -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_SHARED_LIBS=OFF \
  -DBUILD_TESTING=OFF \
  -DENABLE_GTEST=OFF
cmake --build "$HOST_BUILD"

log "collect opencc data"
mkdir -p "$DEST/opencc"
cp "$OPENCC"/data/config/*.json "$DEST/opencc/"
find "$HOST_BUILD" -name '*.ocd2' -exec cp {} "$DEST/opencc/" \;
[[ -n $(find "$DEST/opencc" -name '*.ocd2' -print -quit) ]] \
  || { echo "FATAL: no .ocd2 generated" >&2; exit 1; }

# --- 3. license manifest ---
log "license manifest"
cat > "$DEST/LICENSE-MANIFEST.md" <<EOF
# Baseline Rime data — license manifest

| Asset | Source | License |
| --- | --- | --- |
| default.yaml, key_bindings.yaml, punctuation.yaml, symbols.yaml | [rime-prelude](https://github.com/rime/rime-prelude) @ 082425ea | LGPL-3.0 |
| luna_pinyin*.schema.yaml, luna_pinyin.dict.yaml, pinyin.yaml | [rime-luna-pinyin](https://github.com/rime/rime-luna-pinyin) @ 56b934b0 | LGPL-3.0 |
| essay.txt | [rime-essay](https://github.com/rime/rime-essay) @ e9b1a374 | LGPL-3.0 |
| opencc/*.json, opencc/*.ocd2 | [OpenCC](https://github.com/BYVoid/OpenCC) (librime submodule) | Apache-2.0 |

Full license texts: \`vendor/licenses/\` (project) — data assets above are
covered by their respective upstream LICENSE files; redistribution notice
requirements are met by this manifest plus the bundled license texts.
EOF

# --- 4. summary ---
log "summary"
du -sh "$DEST"
find "$DEST" -type f | wc -l | xargs echo "files:"
du -sh "$DEST/opencc"
